INSERT INTO categories (category_name) VALUES
    ('Fiction'),
    ('Non-Fiction'),
    ('Science'),
    ('History'),
    ('Biography'),
    ('Fantasy'),
    ('Mystery'),
    ('Romance'),
    ('Children\'s Books'),
    ('Cookbooks'),
    ('Art & Design'),
    ('Philosophy'),
    ('Self-Help'),
    ('Health & Wellness'),
    ('Poetry'),
    ('Drama'),
    ('Psychology'),
    ('True Crime'),
    ('Travel'),
    ('Sports'),
    ('Music'),
    ('Technology'),
    ('Business & Economics'),
    ('Politics'),
    ('Religion & Spirituality'),
    ('Science Fiction'),
    ('Graphic Novels'),
    ('Comic Books'),
    ('Horror'),
    ('Parenting');

